title: Cerebrate Life
author:
  name: kuppurao
  email: kuppurao@msn.com
description: > # this means to ignore newlines until "show_excerpts:"
  Here you can find my thoughts on many different topics - but usually around music, technology, economy, but what I value most for my readers are the book reviews. I write them mostly to improve my own retention value of the books I read, sharing it can't possibly be bad. Can it?

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  social_links:
    twitter: kuppurao
    github:  kuppurao
    rss: rss
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    instagram: kuppurao
    linkedin: kuppurao
    # pinterest: jekyll
    # youtube: jekyll
    youtube_channel: UCQHjqTrO5uWJTxm2i_Q_-sQ
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jeklyy
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md
 - music.md

# Build settings
theme: jekyll-theme-hacker

plugins:
 - jekyll-feed
 - jekyll-seo-tag
